### PR TITLE
Fixes for usage

### PR DESCRIPTION
**Pull request by etnKlendathu**

### CODE REVIEW

**Comment by MimiXav** [comment]
I agree with these changes for the first four commit, BUT not for the latest, is there a  consensus for this clang-format proposal?

**Comment by etnKlendathu** [comment]
All other projects in fty namespace (on github) have this formatting. So, IMHO, this project should has the same format. 
If you want to change it later to something else, update clang-format file and run:
`find . -iname *.h -o -iname *.cpp | xargs clang-format-11 -i -style=file`

**Review by MimiXav — APPROVED** [review]

**Comment by perrettecl** [comment]
Will be merged in 2.6.0 as soon the branch is created.

**Comment by perrettecl** [comment]
Will be merge in 2.6.0

**Pull request closed without merging**
